#!/bin/bash

if [[ "$#" != "1" ]] ; then
    echo >&2 "wrong number of args ($#/$@)"
    exit 1
fi
case "$1" in
    "-m")
        echo "x86_64"
        ;;
    "-r")
echo 2.6.32-71.el6.x86_64
        ;;
    *)
        echo >&2 "unexpected arg '$1'"
        ;;
esac
                 
